"""1__14_03_23_10_34

Revision ID: f4818e148a36
Revises: bfd05ee80f9a
Create Date: 2023-03-14 16:04:34.417158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4818e148a36'
down_revision = 'bfd05ee80f9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
